#!/usr/bin/env bash
# session-snapshot: SessionEnd hook — writes a lightweight git/project state
# snapshot to ~/.claude/plans/ so the next session has orientation even without
# a manual /handoff.
#
# - Writes handoff-YYYY-MM-DD-<branch>.md (branch name sanitised for filename).
# - Skips silently if a fresh handoff-*.md was written in the last 30 minutes
#   (i.e. the user already ran /handoff manually this session).
# - Skips silently if the plans dir cannot be created.
# - No stdout or stderr output — purely a file writer.
#
# Part of claude-continuity-kit — https://github.com/reallyunintented/claude-continuity-kit

set -u

PLANS_DIR="${HOME}/.claude/plans"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)

mkdir -p "$PLANS_DIR" 2>/dev/null || exit 0

# Skip if a fresh manual handoff already exists (avoids overwriting /handoff output).
recent=$(find "$PLANS_DIR" -maxdepth 1 -type f -name 'handoff-*.md' \
    -mmin -30 2>/dev/null | head -n1)
[[ -n "$recent" ]] && exit 0

# Git state — silent when not in a repo.
CWD="$PWD"
BRANCH=""
GIT_STATUS=""
GIT_LOG=""

if git -C "$CWD" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    BRANCH=$(git -C "$CWD" branch --show-current 2>/dev/null || echo "detached")
    GIT_STATUS=$(git -C "$CWD" status --short 2>/dev/null | head -20)
    GIT_LOG=$(git -C "$CWD" log --oneline -5 2>/dev/null)
fi

# Sanitise branch name for use in filename.
SLUG="${BRANCH//\//-}"
SLUG="${SLUG//[^a-zA-Z0-9_-]/-}"
SLUG="${SLUG:-snapshot}"

OUTFILE="${PLANS_DIR}/handoff-${DATE}-${SLUG}.md"

# Collect plans list before writing (avoids listing the file mid-write).
OTHER_PLANS=$(find "$PLANS_DIR" -maxdepth 1 -type f -name '*.md' \
    -printf '%T@ %f\n' 2>/dev/null | sort -rn | head -5 | awk '{print $2}')

{
    echo "# Auto-snapshot — ${DATE} ${TIME}"
    echo ""
    echo "> Auto-generated by session-snapshot hook. Not a substitute for \`/handoff\`."
    echo ""
    echo "**Directory:** \`${CWD}\`"

    if [[ -n "$BRANCH" ]]; then
        echo "**Branch:** \`${BRANCH}\`"
        echo ""

        echo "## Uncommitted changes"
        if [[ -n "$GIT_STATUS" ]]; then
            echo '```'
            echo "$GIT_STATUS"
            echo '```'
        else
            echo "_(clean)_"
        fi
        echo ""

        if [[ -n "$GIT_LOG" ]]; then
            echo "## Recent commits"
            echo '```'
            echo "$GIT_LOG"
            echo '```'
            echo ""
        fi
    fi

    if [[ -n "$OTHER_PLANS" ]]; then
        echo "## Plans on disk"
        while IFS= read -r f; do
            echo "- \`${PLANS_DIR}/${f}\`"
        done <<< "$OTHER_PLANS"
        echo ""
    fi
} > "$OUTFILE"

exit 0
